package com.example.db2lineage.model;

public enum RelationshipType {
    CREATE_VIEW,
    CREATE_TABLE,
    CREATE_PROCEDURE,
    CREATE_FUNCTION,

    SELECT_TABLE,
    SELECT_VIEW,
    INSERT_TABLE,
    UPDATE_TABLE,
    MERGE_INTO,
    DELETE_TABLE,
    DELETE_VIEW,
    TRUNCATE_TABLE,
    CALL_FUNCTION,
    CALL_PROCEDURE,

    INSERT_TARGET_COL,
    UPDATE_TARGET_COL,
    MERGE_TARGET_COL,

    SELECT_FIELD,
    SELECT_EXPR,
    UPDATE_SET,

    CREATE_VIEW_MAP,
    INSERT_SELECT_MAP,
    UPDATE_SET_MAP,
    MERGE_SET_MAP,
    MERGE_INSERT_MAP,
    VARIABLE_SET_MAP,
    CURSOR_FETCH_MAP,
    FUNCTION_PARAM_MAP,
    CALL_PARAM_MAP,
    TABLE_FUNCTION_RETURN_MAP,
    SPECIAL_REGISTER_MAP,
    SEQUENCE_VALUE_MAP,
    DIAGNOSTICS_FETCH_MAP,
    FUNCTION_EXPR_MAP,

    WHERE,
    JOIN_ON,
    MERGE_MATCH,
    GROUP_BY,
    ORDER_BY,
    HAVING,
    CONTROL_FLOW_CONDITION,

    CTE_DEFINE,
    CTE_READ,
    UNION_INPUT,
    CURSOR_DEFINE,
    CURSOR_READ,
    EXCEPTION_HANDLER_MAP,

    RETURN_VALUE,
    DYNAMIC_SQL_EXEC,

    UNKNOWN
}
