CREATE OR REPLACE PROCEDURE ADVANCED_DML_PROC ()
LANGUAGE SQL
BEGIN
    DECLARE V_LIMIT INT;
    DECLARE C_UPD CURSOR FOR SELECT STATUS_CD FROM INTERFACE.API_MTM_REVAL FOR UPDATE;
    SET V_LIMIT = GET_MULTIPLIER(5);
    OPEN C_UPD;
    FETCH C_UPD INTO V_LIMIT;
    UPDATE INTERFACE.API_MTM_REVAL SET STATUS_CD = 'X' WHERE CURRENT OF C_UPD;
    CLOSE C_UPD;
END 
@