CREATE OR REPLACE PROCEDURE DEMO_PROC_DB2 ( IN P_ID INT, OUT P_STATUS VARCHAR(50) )
LANGUAGE SQL
BEGIN
    DECLARE V_COUNT INT;
    DECLARE V_SQL VARCHAR(100);
    DECLARE V_CODE INT;
    DECLARE V_TIME TIMESTAMP;

    DECLARE GLOBAL TEMPORARY TABLE SESSION.JOIN_RESULT (
        EMP_ID INT, DEPT_NAME VARCHAR(50), BONUS_AMT DECIMAL(10,2)
    ) ON COMMIT PRESERVE ROWS;

    DECLARE C_EMP CURSOR FOR SELECT EMP_ID FROM EMPLOYEES WHERE DEPT_ID = P_ID;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        SET V_CODE = SQLCODE;
        SET P_STATUS = 'ERROR';
    END;
    SET V_TIME = CURRENT TIMESTAMP;
    SET V_COUNT = 0;
    IF P_ID > 100 THEN
        OPEN C_EMP;
        FETCH C_EMP INTO V_COUNT;
        CLOSE C_EMP;
    END IF;

    INSERT INTO SESSION.JOIN_RESULT (EMP_ID, DEPT_NAME, BONUS_AMT)
    SELECT E.EMP_ID, D.DEPT_NAME, B.AMOUNT
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
    LEFT OUTER JOIN BONUS B  ON E.EMP_ID = B.EMP_ID AND B.YEAR = 2023;

    CALL AUDIT_LOG_PROC(P_ID, 'START');
    SET V_SQL = 'DELETE FROM TEMP_DATA';
    EXECUTE IMMEDIATE V_SQL;
    SET P_STATUS = 'SUCCESS';
END
@