CREATE OR REPLACE PROCEDURE EDGE_CASES_PROC()
LANGUAGE SQL
BEGIN
   DECLARE V_STATUS VARCHAR(50);
   CALL DEMO_PROC_DB2(200, V_STATUS);
   
   -- Simulating a proprietary DB2 command for the UNKNOWN fallback
   REORG TABLE INTERFACE.API_MTM_REVAL;
END
@