CREATE OR REPLACE PROCEDURE INTERFACE.PI_GRAPH_DEMO()
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_GRAPH_STAGE
    (
        COL_A VARCHAR(20)
    )
    WITH REPLACE
    ON COMMIT PRESERVE ROWS;

    INSERT INTO TABLE_A
    (
        COL_A
    )
    SELECT
        S.COL_A
    FROM SESSION.T_GRAPH_STAGE S;

    INSERT INTO TABLE_B
    (
        COL_B
    )
    SELECT
        S.COL_A
    FROM SESSION.T_GRAPH_STAGE S;

    INSERT INTO TABLE_C
    (
        COL_C
    )
    SELECT
        A.COL_A
    FROM TABLE_A A;

    INSERT INTO TABLE_B
    (
        COL_B
    )
    SELECT
        C.COL_C
    FROM TABLE_C C;
END
@
