CREATE OR REPLACE PROCEDURE LOOP_DEMO_PROC (IN P_LIMIT INT)
LANGUAGE SQL
BEGIN
    DECLARE V_COUNTER INT DEFAULT 0;

    -- 1. WHILE Loop using CONTROL_FLOW_CONDITION
    WHILE V_COUNTER < P_LIMIT DO
        SET V_COUNTER = V_COUNTER + 1;
    END WHILE;

    -- 2. FOR Loop (Implicit Cursor) using CURSOR_FETCH_MAP
    FOR V_REC AS SELECT DEAL_NUM, CUR_MTM_AMT FROM INTERFACE.API_MTM_REVAL
    DO
        INSERT INTO SESSION.T_MTM_STAGE (DEAL_NUM, CUR_MTM_AMT)
        VALUES (V_REC.DEAL_NUM, V_REC.CUR_MTM_AMT);
    END FOR;
END
@