CREATE VIEW INTERFACE.V_API_MTM_REVAL AS
SELECT
    F.CUSTOMER_NUMBER AS CUST_NUM,
    F.DEAL_NUMBER     AS DEAL_NUM,
    F.DEAL_TYPE       AS DEAL_TYPE,
    F.MTM_AMOUNT      AS CUR_MTM_AMT,
    F.LAST_UPDATE_TS  AS LAST_UPD_TS
FROM FOS.API_MTM_REVAL F
@
