SELECT
    I.DEAL_TYPE,
    COUNT(*) AS CNT
FROM INTERFACE.API_MTM_REVAL I
JOIN FOS.API_MTM_REVAL F
  ON I.DEAL_NUM = F.DEAL_NUMBER
WHERE I.STATUS_CD = 'ACTIVE'
GROUP BY I.DEAL_TYPE
HAVING COUNT(*) > 1
ORDER BY I.DEAL_TYPE
@

EXECUTE IMMEDIATE 'DELETE FROM INTERFACE.API_MTM_REVAL WHERE STATUS_CD = ''X'''
@
