CREATE TABLE FOS.API_MTM_REVAL (
    CUSTOMER_NUMBER     VARCHAR(20),
    DEAL_NUMBER         VARCHAR(20),
    DEAL_TYPE           VARCHAR(10),
    MTM_AMOUNT          DECIMAL(18,2),
    STATUS_CD           VARCHAR(10),
    LAST_UPDATE_TS      TIMESTAMP
)
@
