CREATE OR REPLACE FUNCTION GET_TOP_DEALS ()
RETURNS TABLE ( OUT_DEAL_NUM VARCHAR(20), OUT_AMT DECIMAL(18,2) )
LANGUAGE SQL
BEGIN
    FOR V_ROW AS
        SELECT DEAL_NUM, SUM(CUR_MTM_AMT) AS TOTAL_AMT
        FROM INTERFACE.API_MTM_REVAL
        GROUP BY DEAL_NUM HAVING SUM(CUR_MTM_AMT) > 1000 ORDER BY DEAL_NUM
    DO
        PIPE ( V_ROW.DEAL_NUM, V_ROW.TOTAL_AMT );
    END FOR;
    RETURN;
END 
@