CREATE OR REPLACE FUNCTION INTERFACE.FN_REL_DEMO
(
    P_CUST_NUM VARCHAR(20)
)
RETURNS VARCHAR(200)
LANGUAGE SQL
READS SQL DATA
BEGIN ATOMIC
    DECLARE V_OUT VARCHAR(200);

    SET V_OUT = (
        SELECT TRIM(V.CUST_NUM) || '-' ||
               INTERFACE.FN_GET_CODE_MAP_VALUE('MTM','STATUS','DEFAULT','A','B')
        FROM INTERFACE.V_API_MTM_REVAL V
        WHERE V.CUST_NUM = P_CUST_NUM
        FETCH FIRST 1 ROW ONLY
    );

    RETURN V_OUT;
END
@
