CREATE OR REPLACE FUNCTION INTERFACE.FN_GET_CODE_MAP_VALUE
(
    P_CODE_CATEGORY      VARCHAR(30),
    P_CODE_SUB_CATEGORY  VARCHAR(30),
    P_CODE_TYPE          VARCHAR(30),
    P_KEY1               VARCHAR(30),
    P_KEY2               VARCHAR(30)
)
RETURNS VARCHAR(100)
LANGUAGE SQL
READS SQL DATA
BEGIN ATOMIC
    DECLARE V_RESULT VARCHAR(100);

    SET V_RESULT = (
        SELECT CODE_VALUE
        FROM CCL.CODE_MAP
        WHERE CODE_CATEGORY = P_CODE_CATEGORY
          AND CODE_SUB_CATEGORY = P_CODE_SUB_CATEGORY
          AND CODE_TYPE = P_CODE_TYPE
          AND KEY1 = P_KEY1
          AND KEY2 = P_KEY2
        FETCH FIRST 1 ROW ONLY
    );

    RETURN COALESCE(V_RESULT, 'NA');
END
@
